generate-permit.ts, package.json, yarn.lock
here is a complete working example for the goerli testnet with all the private keys etc
there are 2 accounts so you could import them, they are already filled with some test ETH and DAI
NOTICE:
DAI doesn't follow https://eips.ethereum.org/EIPS/eip-2612 exactly. It means you can permit ONLY an INFINITE amount of DAI to some user or protocol. While other stablecoins (like USDC) fully comply with EIP-2612 which means you can select what amount to permit to a user or a protocol
=> feat: add goerli example

static/audit.html
Resolves #22 
This PR adds the "audit page" where a treasurer can match issue payout with an ethereum transaction.
How to test:
1. Fill in params (@pavlovcik DMed you params for testing purposes):
2. Click "Get report":
If the concept is fine we can add more features like custom css, retries on error, etc...
=> feat: add audit page

package.json, serve.ts, static/index.html, static/scripts/draw.ts, static/scripts/pay.ts, static/scripts/render-transaction.ts, static/styles/pay.css, yarn.lock
=> Feat: Descriptive Error Message

static/scripts/secret.ts
This PR renames `PSK` to `private-key-encrypted` in the config generation page
=> refactor: rename PSK to private-key-encrypted

static/scripts/secret.ts
resolves https://github.com/ubiquity/pay.ubq.fi/issues/59
I decided not to add a separate text field for `chain-id` to make integration simpler. We don't have a separate field for the `base-multiplier` so perhaps we should keep UI simple without cluttering with unnecessary fields.
=> feat: add chain id to config page

static/scripts/constants.ts, static/scripts/draw.ts, static/scripts/get-contract.ts, static/scripts/globals.d.ts, static/scripts/pay.ts, static/scripts/render-transaction.ts
This approach determines chain id based on the token, DAI for mainnet and WXDAI for gnosis.
Maybe a better approach would be including chain id in the URL parameter when generating a claim url on the bot, which would be cleaner in my opinion.
Resolves #69
=> feat: support for gnosis chain

static/scripts/render-transaction.ts
I realized that this could cause confusion to always assume that the claim is on Ethereum mainnet. Now we must deliberately inform the dApp which network the permit claim is on based on the `?network=100` url parameter. Or else the dApp halts and displays a clear error.
> Error | No network ID passed in URL
=> feat: throw error if no network id in url params

static/index.html, static/scripts/pay.ts
resolves #73 
I fixed the `checkPermitClaimed` because it was not checking just one bit but the whole bitmap, so if two nonces would have the same first 248 bits then the previous algorithm would say that both nonces are claimed even though they are not. In the new version it only checks the bit specified by the last 8 bits of the nonce.
=> Invalidate nonce

static/scripts/onboarding/onboarding.ts
This PR renames the obsolete bot config param `chain-id` to `evm-network-id`
=> refactor: rename chain-id to evm-network-id

static/scripts/audit-report/audit.ts
Fix an early exit from the comment analysis loop and a special case, where the claim permit for the same bounty was generated twice. The audit tool stopped and pointed at the first, wrong permit.
Resolves: #126
QA:
=> fix: display all permitted issues in audit

static/scripts/rewards/render-transaction/insert-table-data.ts, static/scripts/rewards/render-transaction/render-transaction.ts, static/scripts/rewards/render-transaction/tx-type.ts, static/scripts/rewards/web3/erc20-permit.ts, static/scripts/rewards/web3/erc721-permit.ts
Fixed permit types to match the bot's code and fixed naming to make it consistent
=> fix: permit types and naming

.github/workflows/build.yml, .gitmodules, static/onboarding.html, static/scripts/onboarding/onboarding.ts
=> fix: update config types to match the new bot config

.github/workflows/build.yml, .github/workflows/conventional-commits.yml, build/esbuild-build.ts, package.json, scripts/typescript/generate-permit2-url.ts, scripts/typescript/multi-permits.t.ts, static/scripts/audit-report/audit.ts, static/scripts/audit-report/helpers.ts, static/scripts/rewards/constants.ts, static/scripts/rewards/helpers.ts, static/scripts/rewards/render-transaction/insert-table-data.ts, static/scripts/rewards/render-transaction/render-token-symbol.ts, static/scripts/rewards/render-transaction/render-transaction.ts, static/scripts/rewards/web3/erc20-permit.ts, static/scripts/rewards/web3/wallet.ts, yarn.lock
Resolves #168 
The issue with things as far as I could see was that the UI rendering was being held back due to the laggy RPC calls and you'd see this: 
https://github.com/ubiquity/pay.ubq.fi/assets/106303466/bbb7a2a5-a4a6-4de1-96c7-554b2a3ff2f8
Although using the static data available through the permit and hardcoded token info we can see this instead:
https://github.com/ubiquity/pay.ubq.fi/assets/106303466/5ad0b81b-1b70-456d-9a96-d1dbe9f09839
It has involved moving around a few parts but the new interval for the loading ui rendering is sub 1s
With a forked foundry instance, I was trying to replicate the stalling offline to see if I could squeeze a tx through while the stalling rpc calls takes its time but I'm not able to replicate it and work with real permits as local anvil hits …
=> Sub 1s loading UI 

build/esbuild-build.ts, static/scripts/rewards/constants.ts
Resolves #178 
Working locally, follows pattern matching commited by pavlovcik last week, and purge the blacklist thing by the commiter
```
yarn utils:build
yarn start
```
localhost testing
=> chore: remove blacklist

static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/rpc-optimization/get-fastest-rpc-provider.ts, static/scripts/rewards/rpc-optimization/get-optimal-provider.ts
=> fix: rpc networks are tested after selection to make sure they are functional

static/scripts/rewards/rpc-optimization/get-fastest-rpc-provider.ts
Resolves #205 
It worked during the tests because the faulty network was https://gnosis.api.onfinality.io/public. It so happens that there is a similar network at https://gnosis.api.onfinality.io/public_100. I didn't see that the ID of the network would be removed from the key in such case, leading to a `delete` of a key that actually didn't exist during the loop. This has been fixed by storing the untrimmed key in another variable to actually remember the real key value.
=> fix: optimal RPC now removes faulty elements properly

globals.d.ts, static/scripts/rewards/ButtonController.ts, static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/render-transaction/render-transaction.ts, static/scripts/rewards/web3/connect-wallet.ts, static/scripts/rewards/web3/verify-current-network.ts
Resolves https://github.com/ubiquity/pay.ubq.fi/pull/212#issuecomment-2024419599
- - I'm using Brave on ios here
- - I checked out commits about 4 days apart until it would work on mobile without any code changes then applied the changes to the commit in which they were first introduced and verified it would load on mobile. I verified that `development` wouldn't load from HEAD on mobile before merging these changes in and verifying that it would load afterwards
If the issue was that on mobile the UI would never finish loading but would work on a desktop then this resolves it, below are some related infos.
- https://eips.ethereum.org/EIPS/eip-6963
> An alternative discovery mechanism to window.ethereum for [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193) providers which supports …
=> hot-fix: use `window.ethereum`

cypress/e2e/claim-portal-failure.cy.ts, cypress/e2e/claim-portal-non-web3.cy.ts, cypress/scripts/anvil.ts, static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/toaster.ts, static/scripts/rewards/web3/connect-wallet.ts, static/scripts/rewards/web3/erc20-permit.ts
Resolves #220
- the toaster now creates a persistent toast that does not expire when on a non-web3 browser.
- when on mobile the toaster is specific and points them towards a Web3-friendly option
- fully exits the loading state with all details fully rendered
QA:
- Mobile: tested on safari, brave and MM
- Desktop: brave with MM
=> Fix infinite load on non-web3 friendly browsers

.cspell.json, cypress/scripts/anvil.ts, cypress/scripts/funding.ts, package.json, static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/web3/use-rpc-handler.ts
Resolves #229 
- added `rpc-handler` to pull a list of good RPCs to setup anvil with
- added a dedicated script for funding with retries
- improved the anvil setup script with retries 
QA:
- https://github.com/ubq-testing/pay.ubq.fi/actions/runs/9278460006/job/25529499603
=> Improve setup-scripts for tests

cypress/e2e/claim-portal-success.cy.ts, static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/web3/erc20-permit.ts
Resolves #227 
- correct prop access typo
- add test for invalidate functionality
=> fix: prop access and added test

static/scripts/rewards/web3/connect-wallet.ts
Resolves #243 
You were right @0x4007 and I was over thinking it. We've already passed the url check and built the `appState` so this looks to resolve things.
https://github.com/ubiquity/pay.ubq.fi/assets/106303466/95a093b3-056d-470f-9b08-5c427c6bc173
=> fix: clear url param after load

scripts/typescript/generate-erc20-permit-url.ts
I've been trying to generate permits for USDT with 6 decimals which ended up converting to a wrong number. 
This PR takes into account token decimals when generating test permits.
=> fix: call decimals() on generating test permits

static/index.html, static/scripts/rewards/render-transaction/render-transaction.ts, static/styles/rewards/claim-table.css
Resolves #247
The add. table is well placed and it didn't feel right moving it up any further
- applies `transform` and moves `mainTableBody` into sight only for NFTs
Before:
https://github.com/ubiquity/pay.ubq.fi/assets/106303466/8566ed05-0dca-45f7-b95f-9eece705066c
After:
https://github.com/ubiquity/pay.ubq.fi/assets/106303466/27661f1f-359e-4cd9-8156-b5e4776d17a2
=> fix: move controls into sight

.github/workflows/build.yml, .github/workflows/deploy.yml
Resolves https://github.com/ubiquity/cloudflare-deploy-action/pull/13#issuecomment-2175648131
Github uses `deploy.yml` only from the default branch `development`. We need this in the default branch to work for both, our new and old code from https://github.com/ubiquity/pay.ubq.fi/pull/226
Can we merge this asap to try it?
=> fix: use new deploy workflow to use new naming

.cspell.json, README.md, cypress.config.ts, cypress/e2e/claim-portal-non-web3.cy.ts, cypress/e2e/claim-portal-success.cy.ts, static/scripts/rewards/web3/connect-wallet.ts, static/scripts/rewards/web3/erc20-permit.ts
Fixes `CSpell` and `Eslint` errors
https://github.com/ubiquity/pay.ubq.fi/actions/runs/9915811203/job/27397264529
=> fix(ci): cspell and eslint fixes

.cspell.json, functions/list-gift-cards.ts, functions/post-order.ts, package.json, shared/helpers.ts, static/index.html, static/scripts/rewards/gift-cards/gift-card.ts, static/scripts/rewards/gift-cards/helpers.ts, static/scripts/rewards/gift-cards/list-gift-cards.ts, static/styles/rewards/gift-cards.css, static/styles/rewards/pay.css, wrangler.toml, yarn.lock
Resolves #259
[QA](https://github.com/ubiquity/pay.ubq.fi/pull/270#issuecomment-2266103136)
=> PR: offer virtual cards by user location

build/esbuild-build.ts
=> fix: multiplatform support

cypress/e2e/claim-portal-failure.cy.ts, cypress/e2e/claim-portal-non-web3.cy.ts, cypress/e2e/claim-portal-success.cy.ts, static/index.html, static/scripts/rewards/app-state.ts, static/scripts/rewards/init.ts, static/scripts/rewards/render-transaction/claim-rewards-pagination.ts, static/scripts/rewards/render-transaction/insert-table-data.ts, static/scripts/rewards/render-transaction/read-claim-data-from-url.ts, static/scripts/rewards/render-transaction/render-ens-name.ts, static/scripts/rewards/render-transaction/render-token-symbol.ts, static/scripts/rewards/render-transaction/render-transaction.ts, static/scripts/rewards/render-transaction/utils.ts, static/scripts/rewards/toaster.ts, static/scripts/rewards/web3/connect-wallet.ts, static/scripts/rewards/web3/erc20-permit.ts, static/scripts/rewards/web3/erc721-permit.ts, static/scripts/rewards/web3/handle-if-on-correct-network.ts, static/scripts/rewards/web3/not-on-correct-network.ts, static/scripts/rewards/web3/switch-network.ts, static/scripts/rewards/web3/use-rpc-handler.ts, static/scripts/rewards/web3/verify-current-network.ts, static/styles/rewards/claim-table.css, static/styles/rewards/light-mode.css, static/styles/rewards/pay.css
Reverts ubiquity/pay.ubq.fi#274
Styles are still messed up. It's not centered. These details need to be addressed.
=> Revert "feat: vertically stacked permits"

.cspell.json, static/scripts/rewards/web3/erc20-permit.ts
This should make the UI appear quicker because we are no longer awaiting the transaction to be confirmed onchain before allowing the tx be viewed on a block explorer. The loading mechanic once the wallet prompt is confirmed should disappear almost instantly as we have the `tx.hash` already. 
- render the `view claim` button before we await the `tx`
- still produce the success toast after we await the `tx`
=> optimistic view claim rendering

.cspell.json, .github/workflows/sync-template.yml, package.json, static/scripts/rewards/web3/erc20-permit.ts
I added a little delay effect, no autographs please
https://github.com/user-attachments/assets/275d4bc6-b429-4d96-8600-05fa9bcfbc06
=> View claim

static/scripts/rewards/render-transaction/insert-table-data.ts
=> feat: handle large numbers in details table

static/styles/rewards/pay.css
Resolves https://github.com/ubiquity/pay.ubq.fi/issues/339
I've double checked all of the css styles changes between "pre gift card mint" and "post gift card mint" branches:
- logo css styles are restored
- all other css styles are inplace (almost untouched)
=> style: restore logo css

functions/helpers.ts
This PR uses a proxy URL with whitelisted ip in reloadly dashboard for minting real gift cards.
I've tried to add it to env variable but it followed a whole bunch of refactors because we have to pass the `ctx.env` object literally to all of the helper methods. I'll address it in a separate PR.
Notes:
1. This is a temporary solution since we need reloadly gift cards to be working for https://githubuniverse.com/
2. The `web3-gateway-test.com` domain DNS is not yet resolved for some of the countries. For example, it doesn't work in Germany and Belgium, but does work in Latvia.
=> feat: use reloadly production proxy

functions/get-order.ts, functions/get-redeem-code.ts, functions/post-order.ts, shared/api-types.ts, shared/helpers.ts, static/scripts/rewards/gift-cards/mint/mint-action.ts, static/scripts/rewards/gift-cards/mint/mint-tx-tracker.ts, static/scripts/rewards/gift-cards/reveal/reveal-action.ts, static/scripts/ubiquity-dollar/gift-card.ts, tests/unit/post-order.test.ts
Resolves #291
In issue specs, I suggested retrieving the transaction hash of the partially failed mint by reading the events of permit2. I tried that. Even though permit2 has events, but none of those events are for the claim. Because of this, the events of permit2 are of no use to us here.
In the current solution, we store the permit nonce and tx hash in local storage and use it in retry if the mint failed previously. This is good enough for us.
However, there is one drawback of this solution. When minting, the user has to provide two confirmations using their web3 wallet. One for the permit transaction, and the second to sign a message.   Moreover, the signing of message also provides an additional benefit. `/post-order` is open to public and anyone can call it if the transaction has …
=> PR: retry mint for a failed payment card order
