- .github/workflows/cloudflare.yml
- README.md
https://dash.cloudflare.com/***/pages
https://dash.cloudflare.com/abcd1234/pages
(Here `abcd1234` is your account ID)
https://dash.cloudflare.com/profile/api-tokens > Create Token > API token templates > Edit Cloudflare Workers > Use Template
Account Resources = All Accounts or Target Account
Zone Resources = All Zones
(Detailed Instructions: https://developers.cloudflare.com/workers/wrangler/ci-cd/)
static
npm install -g wrangler
wrangler login
wrangler pages project create
deployment: https://6c79ddec.pay-ubq-fi.pages.dev/
Resolves #26
> Fix: CloudFlare Deploy

- build.ts
- package.json
- static/audit.html
- static/scripts/audit.ts
- static/styles/audit.css
- yarn.lock
> Feat(Audit): Typescript and Vanilla CSS

- static/scripts/pay.ts
> Decimal check

- static/audit.html
- static/scripts/audit.ts
- static/scripts/types/audit.d.ts
- static/styles/audit.css
```
Clear [🌐site] && [🍪cookies]
```
Resolves #45
> Feat: Prettify URLs

- static/scripts/entries.ts
- static/scripts/secret-compact.ts
- static/secret-compact.html
- static/styles/sec.css
> Feat: Better Keychain

- static/scripts/secret.ts
This PR:
1. Uses kebab case config params introduced here: https://github.com/ubiquity/bounty-bot/pull/282
2. Adds a new `max-concurrent-bounties` config param
P.S. this PR is a subtask for https://github.com/ubiquity/bounty-bot/issues/299
> feat: use kebab case for config params

- static/scripts/pay.ts
This PR adds support for payouts in gnosis chain
> feat: add gnosis chain support

- test/Permit2.t.sol
This PR adds test for [nonce invalidation](https://github.com/Uniswap/permit2/blob/main/src/SignatureTransfer.sol#L130)
> test: add nonce invalidation test

- .github/workflows/continuous-deploy.yml
https://github.com/ubiquity/pay.ubq.fi/pull/76#issuecomment-1605401823
> fix: convert periods to hyphens in repo names

- .github/workflows/build.yml
- server.ts
> fix: commit hash on ci cd deploys

- .github/workflows/build.yml
- .github/workflows/continuous-deploy.yml
This PR implements reusable deploy from https://github.com/ubiquity/.github/pull/79
> Reusable deploy

- static/scripts/rewards/web3/invalidate-nonce.ts
Fixes incorrect permit invalidation, more info [here](https://github.com/ubiquity/pay.ubq.fi/issues/73#issuecomment-1669185783)
> fix: fix permit invalidation

- static/scripts/onboarding/onboarding.ts
> Feat: Remotely Fetch Default Config

- static/keygen.html
- static/scripts/key-generator/keygen.ts
public key will be derived from private key if it's supplied
> feat: derive public key

- .github/workflows/build.yml
- .github/workflows/conventional-commits.yml
I was working on it this week over at `@ubiquity/ts-template` and `@ubiquity/cloudflare-continuous-deploys`.
It is almost in its final state - its just exposing secrets but theres [a task](https://github.com/ubiquity/cloudflare-deploy-action/issues/1) to address this.
> fix: continuous deploys

- build/esbuild-build.ts
> fix: extraRpcs declaration error

- .github/workflows/build.yml
- .github/workflows/deploy.yml
This PR fixes cloudflare preview deployments
> ci: use latest cloudflare deploy

- static/scripts/rewards/render-transaction/render-token-symbol.ts
Resolves #210 
QA:
`95.255555`
`95`
> fix: decimals

- .github/workflows/deploy.yml
- README.md
> fix: deploy workflow properly posts urls to the deployment

- static/scripts/rewards/web3/connect-wallet.ts
Resolves #256
Manually QA'd desktop and mobile with both working as expected
> fix: remove param for mobile only

- static/scripts/rewards/app-state.ts
> chore: use blockscan for multichain balance overview

- .cspell.json
- static/scripts/rewards/web3/erc20-permit.ts
Reverts ubiquity/pay.ubq.fi#290
> Revert "optimistic view claim rendering"

- .cspell.json
This PR fixes [this](https://github.com/ubiquity/pay.ubq.fi/actions/runs/10856038538/job/30129906066?pr=302) CI error
> ci: fix cspell

- static/scripts/rewards/cirip/ens-lookup.ts
- static/scripts/rewards/cirip/fetch-ens.ts
- static/scripts/rewards/cirip/query-graph.ts
- static/scripts/rewards/cirip/query-reverse-ens.ts
Reverts ubiquity/pay.ubq.fi#297
> Revert "fix: ens lookup"

- .cspell.json
- .github/.ubiquibot-config.yml
This PR enables gnosis [UUSD](https://gnosisscan.io/address/0xc6ed4f520f6a4e4dc27273509239b7f8a68d2068) payouts for current repository.
> chore: create `.ubiquibot-config.yml`

- static/styles/rewards/media-queries.css
- static/styles/rewards/pay.css
> Scroll issue

- static/scripts/rewards/app-state.ts
- static/scripts/rewards/render-transaction/render-transaction.ts
TLDR; This PR fixes broken explorer URLs 
Resolves https://github.com/ubiquity/pay.ubq.fi/pull/320#pullrequestreview-2362295622
> fix: show explorer URLs

- static/scripts/rewards/cirip/query-reverse-ens.ts
Resolves https://github.com/ubiquity/pay.ubq.fi/issues/305
> refactor: use rpc-handler for ENS lookups

- .github/workflows/deploy.yml
> feat: fix deploy runner name check

- .github/.ubiquity-os.config.yml
This PR updates the `publicAccessControl` setting in the `daemon-pricing` configuration to `false`.
> chore: update configuration
